### ISSUE TITLE
ModuleNotFoundError: No module named "Crypto"

### ISSUE THREAD

**Issue by OAS33** [sam-astro/vault#1]
After installing pycryptodome, Crypto and crypto I still get the error;

`
Traceback (most recent call last):
  File "C:\vault\main.py", line 5, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
`

python version: 3.10.8
pip version: 22.3
pycryptodome version: 3.15.0

**Comment by sam-astro** [comment]
Sorry I haven't put a list of packages yet. I think that one might just be `pycrypto`
